services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    # 필요하다면 환경 변수나 볼륨 설정도 추가 가능
    # volumes:
    #   - ./redis-data:/data

  web:
    image: nginx:latest
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
    volumes:
      # 아래 nginx.conf 파일을 직접 작성해두면 됩니다. (예: 동일 디렉터리)
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # 정적 파일(HTML, CSS, JS 등)을 배포하고 싶다면 html 디렉터리를 마운트합니다.
      - ./html:/usr/share/nginx/html:ro
