name: Build and Deploy on develop

on:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스코드 체크아웃 (Actions 내부에서 빌드 테스트/CI 필요한 경우)
      #    - 만약 서버에서만 git pull 하면 이 스텝은 생략해도 됨.
      - name: Check out code
        uses: actions/checkout@v2

      # 2) (선택) Java 세팅 & Gradle 빌드 (Actions에서 빌드 테스트하려면)
      #    - 서버 쪽에서만 빌드할 거면, 이 단계도 생략 가능
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      # 3) SSH로 EC2 서버 접속 → 원격에서 애플리케이션 재배포
      - name: SSH into server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: 22
          script: |
            # 1) 서버에 배포 디렉토리로 이동
            cd /home/ubuntu/boheommong_back

            # 2) 깃 pull로 최신 코드 가져오기 (develop 브랜치)
            git pull origin develop

            # 3) 기존 프로세스 종료 (java -jar로 실행 중이라면)
            pkill -f 'java -jar' || true

            # 4) Gradle 빌드 (서버에서 직접 빌드)
            ./gradlew clean build

            # 5) 새로 실행 (백그라운드 실행 예시 - nohup)
            nohup java -jar build/libs/boheommong.jar --server.port=8080 &
