name: CI/CD

on:
  pull_request:
    branches: [ develop ]   # PR이 develop 브랜치 대상으로 열릴 때
  push:
    branches: [ develop ]   # 머지 완료 후 develop에 커밋이 생길 때

jobs:
  # 1) PR 검증 용도
  test:
    # pull_request일 때만 동작
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    env:
      MYSQLDB_USERNAME: ${{ secrets.MYSQLDB_USERNAME }}
      MYSQLDB_PASSWORD: ${{ secrets.MYSQLDB_PASSWORD }}
      MYSQLDB_ROOT_PASSWORD: ${{ secrets.MYSQLDB_ROOT_PASSWORD }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_SECRET_KEY_CODE: ${{ secrets.JWT_SECRET_KEY_CODE }}
      KAKAO_OAUTH_CLIENT_SECRET: ${{ secrets.KAKAO_OAUTH_CLIENT_SECRET }}
      KAKAO_OAUTH_CLIENT_ID: ${{ secrets.KAKAO_OAUTH_CLIENT_ID }}
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build and test
        run: |
          ./gradlew clean test

  # 2) 실제 배포
  deploy:
    # push (즉, develop에 최종 커밋) 이벤트일 때만 실행
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    env:
      MYSQLDB_USERNAME: ${{ secrets.MYSQLDB_USERNAME }}
      MYSQLDB_PASSWORD: ${{ secrets.MYSQLDB_PASSWORD }}
      MYSQLDB_ROOT_PASSWORD: ${{ secrets.MYSQLDB_ROOT_PASSWORD }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_SECRET_KEY_CODE: ${{ secrets.JWT_SECRET_KEY_CODE }}
      KAKAO_OAUTH_CLIENT_SECRET: ${{ secrets.KAKAO_OAUTH_CLIENT_SECRET }}
      KAKAO_OAUTH_CLIENT_ID: ${{ secrets.KAKAO_OAUTH_CLIENT_ID }}
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: ./gradlew clean build

      - name: SSH into server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/back
            git pull origin develop
            pkill -f 'java -jar' || true
            ./gradlew clean build
            nohup java -jar build/libs/boheommong.jar --server.port=8080 &
