name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21

      - name: Build
        run: ./gradlew clean build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 예: 기존 프로세스 종료, 새 JAR 업로드, 실행
            pkill -f 'java -jar' || true
            rm -rf /home/ec2-user/myapp.jar
            # GitHub Actions artifact를 SCP로 옮기거나, 또는 actions-ssh로 직접 전달
            # ...
            nohup java -jar /home/ec2-user/myapp.jar > /dev/null 2>&1 &
